mutation CREATE_ORDER_CART($UID: String, $ANALIZES: [ID], $USER: [ID], $SUMM: Long, $OFFICE: [ID], $PROMO: String) {
  createOrder(
    data: { 
      UID: $UID, 
      analizies: $ANALIZES, 
      users: $USER, 
      SummOrder: $SUMM, 
      Status: false,
      ofisies: $OFFICE,
      PromoVrach: $PROMO }
  ) {
    data {
      id
      attributes {
				UID
      }
    }
  }
}
