query GET_SITY_ID($ID : ID) {
  sityesInvitro(id: $ID) {
      data {
      id
      attributes {
        Name
        area_invitros(filters: { Invitro: { eq: true } }) {
          data {
            id
            attributes {
              Invitro
              Name
              goroda_invitros(filters: { Invitro: { eq: true } }) {
                data {
                  id
                  attributes {
                    Invitro
                    Name
                   GegimRaboty
                    Phone
                    Coords
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
