mutation SET_USER_TO_VRACH($ID_VRACH: ID!, $ID_USERS: [ID]){
  updateUsersPermissionsUser (id: $ID_VRACH, data: { Pacientis: $ID_USERS }) {
    data {
      attributes {
        FIO_user
        Pacientis {
          data {
            id
            attributes {
              FIO_user
            }
          }
        }
      }
    }
  }
}