query PRODUCTS_CAT($ID_CAT: String) {
  analizies(pagination: { pageSize: 25 },
  filters: {sub_cat : {URL: { eq: $ID_CAT}}}) {
    meta{
      pagination{
        page
        pageCount
        pageSize
        total
      }
    }
    data{
      id
      attributes{
        Name
        Art
        Price
        TimeDone
        Complecs
        Active
        complecsAnaliz {
          data {
            id
            attributes {
              Name
              Price
              Art
              Active
            }
          }
        }
        DopAnalizes{
          data{
            id
          }
        }
        sub_cat{
            data{
              attributes{
                Name
                URL
                CatIdURL
              }
            }
          }
        biomaterialies{
          data{
            id
            attributes{
              Price
              Name
            }
          }
        }
      }
    }
  }
}