query SEARCH_ANALIZES($S_VALUE : String!) {
  search (query : $S_VALUE){
    analizies {
      data{
          id
        attributes{
          Name
          Art
          TimeDone
          Price
          Complecs
          Active
          Tags
          DopAnalizes{
          data{
            id
            attributes {
              Name
              Price
              Art
              biomaterialies{
          data{
            id
            attributes{
              Name
              Price
            }
          }
        }
            }
          }
        }
        biomaterialies{
          data{
            id
            attributes{
              Price
              Name
            }
          }
        }
          sub_cat{
            data{
              attributes{
                Name
                URL
                CatIdURL
              }
            }
          }
        }
      }
    }
  }
}