query GET_ME($ID: ID) {
  usersPermissionsUser(id: $ID) {
    data {
      attributes {
        FIO_user
        zakazies(pagination: { limit: 100 }) {
          data {
            id
            attributes {
              Status
              StatusOplata
              SummOrder
              UID
               analizies{
                data{
                  id
                  attributes{
                    TimeDone
                  }
                }
              }
              Result {
                data {
                  attributes {
                    url
                    name
                  }
                }
              }
              createdAt
            }
          }
        }
      }
    }
  }
}
