query SLIDER_ALL {
  sliders{
    data{
      attributes{
        Link
        Name
        Photo{
          data{
            attributes{
              url
            }
          }
        }
      }
    }
  }
}