mutation REGISTER_DOCTOR_FIRST($USERNAME: String!, $EMAIL: String!, $PASS: String!) {
  register(input: { username: $USERNAME, email: $EMAIL, password: $PASS }) {
    user {
      id
      username
    }
  }
}