mutation CREATE_DOCTOR(
    $ID: ID!
    $FIO: String
    $PHONE: String
    $DATAROZHDENIYA: String
    $GENDER: Boolean
    $PROMO: String
    $SPEC: [ID]
    $OFIC: [ID]
) {
  updateUsersPermissionsUser(
    id: $ID
    data: {
      FIO_user: $FIO
      RoleUser: "Vrach"
      Phone: $PHONE
      DataRozgdeniya: $DATAROZHDENIYA
      Promo: $PROMO
      Gender: $GENDER
      blocked: false
      Stavka: 15
      speczialnosts :  $SPEC
      ofisies: $OFIC
    }
  ) {
    data {
      id
      attributes {
        FIO_user
        email
        Promo
        blocked
      }
    }
  }
}
