query VIG_ANALIZ {
  vigAnalizs {
    data {
      id
      attributes {
        analizy {
          data {
            attributes {
              Name
              Art
            }
          }
        }
        Link
        Price
      }
    }
  }
}
