query VIG_COMPLECS {
  vigComplecs(pagination: {pageSize: 100}) {
    data {
      id
      attributes {
        analizy {
          data {
            attributes {
              Name
              Art
            }
          }
        }
        Link
        Price
      }
    }
  }
}
